# Generated by Django 5.2.1 on 2025-09-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-featured', 'order', '-uploaded_at')},
        ),
        migrations.AddField(
            model_name='event',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
