# Generated by Django 5.2.1 on 2025-09-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_event_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
