# Generated by Django 5.2.1 on 2025-06-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='video',
            new_name='URL',
        ),
        migrations.AddField(
            model_name='event',
            name='url_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
