# Generated by Django 5.2.1 on 2025-05-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_file_remove_event_image_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tagline',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
