# Generated by Django 5.2.1 on 2025-06-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_event_date_remove_event_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
