# Generated by Django 5.2.1 on 2025-05-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tagline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
