# Generated by Django 5.2.1 on 2025-06-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_video_event_url_event_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
