# Generated by Django 5.2.1 on 2025-05-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
