# Generated by Django 5.2.1 on 2025-06-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='banner_image',
        ),
    ]
