# Generated by Django 5.2.1 on 2025-06-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourceimage',
            old_name='image',
            new_name='img',
        ),
    ]
