# Generated by Django 5.2.1 on 2025-09-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('order', '-uploaded_at')},
        ),
        migrations.AddField(
            model_name='resource',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
