# Generated by Django 5.2.1 on 2025-06-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
