# Generated by Django 5.2.1 on 2025-06-15 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_rename_image_resourceimage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceimage',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='resourceimage',
            name='is_banner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='resourceimage',
            name='is_thumbnail',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='resources.resource'),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
