# Generated by Django 5.2.1 on 2025-09-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_options_resource_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('position', '-uploaded_at')},
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='order',
            new_name='position',
        ),
    ]
