# Generated by Django 5.2.1 on 2025-06-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resourceimage_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourceimage',
            old_name='img',
            new_name='image',
        ),
    ]
