# Generated by Django 5.2.1 on 2025-09-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='position',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
