# Generated by Django 5.2.1 on 2025-06-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='video',
            new_name='URL',
        ),
    ]
