# Generated by Django 5.2.1 on 2025-06-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_rename_video_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='url_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
