# Generated by Django 5.2.1 on 2025-06-17 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_resource_url_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('Resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='resources.resource')),
            ],
        ),
    ]
